language: java
jdk:
- openjdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build
  - ./webapp/gradlew test

notifications:
  username:
    recipients:
      - zhang.yichu@husky.neu.edu
