language: java
jdk:
- openjdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build
  - gradle webapp/test -Dtest.single=ApplicationTest
notifications:
  username:
    recipients:
      - zhang.yichu@husky.neu.edu
