language: java
jdk:
- oraclejdk8

sudo: false
install: true

branches:
  only:
  - lab

script:
  - cd webapp
  - ./gradlew war

after_success:
 - mkdir codedeploy
 - zip -r lab-$TRAVIS_JOB_NUMBER.zip build/libs/ROOT.war infrastructure/aws/codedeploy/ appspec.yml
 - ls -al
 - mv lab-$TRAVIS_JOB_NUMBER.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd
 - cd ..
 - pwd
