language: java
jdk:
- oraclejdk8

sudo: false
install: true

branches:
  only:
  - lab

script:
  - pwd
  - cd webapp
  - ./gradlew war
  - cd ..
  - pwd
  - ls -al

after_success:
 - mkdir codedeploy
 - zip -r lab-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war infrastructure/aws/codedeploy/ appspec.yml
 - ls -al
 - mv lab-$TRAVIS_JOB_NUMBER.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd
 - cd ..
 - pwd

deploy:
 - provider: s3
   local_dir: codedeploy
   bucket: xiaoli.csye6225.com
   region: us-east-1
   skip_cleanup: true
   access_key_id: $access_key_id
   secret_access_key: $secret_access_key
   on:
     branch: lab 
