language: java
jdk:
- oraclejdk8

sudo: false
install: true

branches:
  only:
  - lab

script:
  - ./gradlew war

after_success:
 - mkdir codedeploy
 - zip -r lab.zip build/libs/ROOT.war appspec.yml
 - ls -al
 - mv lab.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd
 - cd ..
 - pwd
