language: java
jdk:
- openjdk8

sudo: false
install: true

script:
- cd webapp
- ./gradlew war

notifications:
  username:
    recipients:
      - li.xiao5@husky.neu.edu
    on_success: always
    on_failure: always
