version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps
  - source: ./awslogs.conf
    destination: /home/ubuntu
  - source: ./restartawslogsservice.sh
    destination: /home/ubuntu

hooks:
  AfterInstall:
   - location: ./restartTomcat.sh
     timeout: 180
     runas: ubuntu
   - location: ./restartawslogsservice.sh
     timeout: 300
     runas: ubuntu